version: '2'

services:
  web:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment: 
        EMAIL_SMTP_USERNAME: "${EMAIL_SMTP_USERNAME}"
        EMAIL_SMTP_PASSWORD: "${EMAIL_SMTP_PASSWORD}"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db