apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: web
    spec:
      containers:
      - env:
        - name: EMAIL_SMTP_PASSWORD
          value: "${EMAIL_SMTP_PASSWORD}"
        - name: EMAIL_SMTP_USERNAME
          value: "${EMAIL_SMTP_USERNAME}"
        image: web
        imagePullPolicy: ""
        name: web
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: web-claim0
        - mountPath: /app/node_modules
          name: web-claim1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
      - name: web-claim1
        persistentVolumeClaim:
          claimName: web-claim1
status: {}
